### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by AccelQuasarDragon** [kivy-school/kivy-reloader#6]
- [ ] use multiprocessing to compile stuff
- [ ] how to add a library w/o recompiling EVERYTHING
- [ ] qr code to get adb to stream apk FROM THE PHONE (so not terminal command but just scan qr code to visit an adb address to stream apk and then kivy picks it up and goes from there) FROM TERMINAL
